-- Product catalog seed — the single source of truth for the storefront's
-- products. Run on every boot by seedProductsFromSql() in seed.ts. Idempotent
-- full upsert:
--   * fresh DB    → all rows inserted
--   * existing DB → new ids inserted; seeded ids (1–44) are fully synced to the
--                   values below (title, price, image, …). Admin-ADDED products
--                   (id ≥ 45) aren't listed here, so they're never touched.
-- Prices are in INR (whole rupees). image_url is real cover art / console photo.
INSERT INTO products
  (id, title, type, platform, "condition", price, original_price, rating, emoji, accent, image_url, description, wikipedia_url, steam_appid)
VALUES
  (1, 'Elden Ring', 'game', 'PlayStation', 'Mint', 2904, 4979, 4.9, '⚔️', 'from-amber-500/30 to-brand/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/library_600x900.jpg', 'Elden Ring is a 2022 action role-playing game directed by Hidetaka Miyazaki with worldbuilding provided by the American fantasy writer George R. R. Martin. Developed by FromSoftware and published by Bandai Namco Entertainment, it was first released on February 25, 2022 for PlayStation 4…', 'https://en.wikipedia.org/wiki/Elden_Ring', 1245620),
  (2, 'God of War Ragnarök', 'game', 'PlayStation', 'Good', 2489, 4149, 4.8, '🪓', 'from-blue-500/30 to-cyan-400/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/library_600x900.jpg', 'God of War Ragnarök is a 2022 action-adventure game developed by Santa Monica Studio and published by Sony Interactive Entertainment. It was released worldwide on November 9, 2022, for both the PlayStation 4 and PlayStation 5, marking the first cross-generation release in the God of War series, and…', 'https://en.wikipedia.org/wiki/God_of_War_Ragnar%C3%B6k', 2322010),
  (3, 'The Legend of Zelda: Tears of the Kingdom', 'game', 'Nintendo', 'Mint', 3734, 5809, 4.9, '🗡️', 'from-emerald-500/30 to-lime-400/30', 'https://upload.wikimedia.org/wikipedia/en/f/fb/The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg', 'The Legend of Zelda: Tears of the Kingdom is a 2023 action-adventure game developed by Nintendo EPD for the Nintendo Switch. The player controls Link as he searches for Princess Zelda and fights to prevent Ganondorf from destroying Hyrule.', 'https://en.wikipedia.org/wiki/The_Legend_of_Zelda%3A_Tears_of_the_Kingdom', NULL),
  (4, 'Mario Kart 8 Deluxe', 'game', 'Nintendo', 'Good', 3319, 4979, 4.7, '🏎️', 'from-red-500/30 to-orange-400/30', 'https://upload.wikimedia.org/wikipedia/en/b/b5/MarioKart8Boxart.jpg', 'Mario Kart 8 is a 2014 kart racing game developed and published by Nintendo for the Wii U. It retains the gameplay of previous Mario Kart games, with players controlling characters from the Mario series and other Nintendo characters in races around tracks.', 'https://en.wikipedia.org/wiki/Mario_Kart_8', NULL),
  (5, 'Halo Infinite', 'game', 'Xbox', 'Fair', 1659, 4149, 4.3, '🪖', 'from-green-500/30 to-teal-400/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/library_600x900.jpg', 'Halo Infinite is a 2021 first-person shooter game developed by 343 Industries and published by Xbox Game Studios. It is the sixth mainline installment in the Halo series, following Halo 5: Guardians (2015).', 'https://en.wikipedia.org/wiki/Halo_Infinite', 1240440),
  (6, 'Cyberpunk 2077', 'game', 'PC', 'Good', 2074, 4979, 4.5, '🌆', 'from-yellow-400/30 to-fuchsia-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/library_600x900.jpg', 'Cyberpunk 2077 is a 2020 action role-playing game developed by CD Projekt Red and published by CD Projekt. Based on Mike Pondsmith''s Cyberpunk tabletop game series, the plot is set in the fictional metropolis of Night City in California, within the dystopian Cyberpunk universe.', 'https://en.wikipedia.org/wiki/Cyberpunk_2077', 1091500),
  (7, 'Forza Horizon 5', 'game', 'Xbox', 'Mint', 2738, 4979, 4.8, '🚗', 'from-purple-500/30 to-pink-400/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/library_600x900.jpg', 'Forza Horizon 5 is a 2021 racing game developed by Playground Games and published by Xbox Game Studios. It is the fifth Forza Horizon title, following Forza Horizon 4, and the twelfth main instalment in the Forza series.', 'https://en.wikipedia.org/wiki/Forza_Horizon_5', 1551360),
  (8, 'Baldur’s Gate 3', 'game', 'PC', 'Mint', 3319, 4979, 5.0, '🐉', 'from-rose-500/30 to-amber-400/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/library_600x900.jpg', 'Baldur''s Gate 3 is a role-playing video game by Larian Studios. It is the third installment in the Baldur''s Gate series.', 'https://en.wikipedia.org/wiki/Baldur''s_Gate_3', 1086940),
  (9, 'PlayStation 5 (Slim)', 'console', 'PlayStation', 'Good', 31539, 41499, 4.8, '🎮', 'from-blue-600/40 to-indigo-500/30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Black_and_white_Playstation_5_base_edition_with_controller.png/960px-Black_and_white_Playstation_5_base_edition_with_controller.png', 'The PlayStation 5 (PS5) is a home video game console developed by Sony Interactive Entertainment as the fifth iteration of their PlayStation brand. It was announced as the successor to the PlayStation 4 in April 2019, and was launched in Australia, Japan, New Zealand, North America, and South Korea…', 'https://en.wikipedia.org/wiki/PlayStation_5', NULL),
  (10, 'Xbox Series X', 'console', 'Xbox', 'Mint', 33199, 41499, 4.9, '🟩', 'from-green-600/40 to-emerald-500/30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Xbox_Series_X_2.jpg/960px-Xbox_Series_X_2.jpg', 'The Xbox Series X and Xbox Series S are the fourth generation of consoles in Microsoft''s Xbox series, succeeding the previous generation''s Xbox One. Released on November 10, 2020, the higher-end Series X and lower-end Series S are part of the ninth generation of video game consoles, which also…', 'https://en.wikipedia.org/wiki/Xbox_Series_X_and_Series_S', NULL),
  (11, 'Nintendo Switch OLED', 'console', 'Nintendo', 'Good', 24069, 29049, 4.7, '🕹️', 'from-red-500/40 to-rose-400/30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Nintendo_Switch_%E2%80%93_OLED-Modell%2C_Konsole_und_Dock_20230506.png/960px-Nintendo_Switch_%E2%80%93_OLED-Modell%2C_Konsole_und_Dock_20230506.png', 'The 2021 revision of the Nintendo Switch, with a larger 7-inch OLED screen, a wider adjustable stand and 64 GB of internal storage.', 'https://en.wikipedia.org/wiki/Nintendo_Switch', NULL),
  (12, 'PlayStation 4 Slim', 'console', 'PlayStation', 'Fair', 12449, 24899, 4.2, '🎮', 'from-slate-500/40 to-blue-400/30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/PS4-Console-wDS4.jpg/960px-PS4-Console-wDS4.jpg', 'The PlayStation 4 (PS4) is a home video game console developed by Sony Interactive Entertainment. Announced as the successor to the PlayStation 3 in February 2013, it was launched on November 15, 2013, in North America, November 29, 2013, in Europe, South America, and Australia, and on February 22…', 'https://en.wikipedia.org/wiki/PlayStation_4', NULL),
  (13, 'Xbox Series S', 'console', 'Xbox', 'Good', 18259, 24899, 4.6, '⬜', 'from-neutral-400/40 to-emerald-400/30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Xbox_Series_S_with_controller.jpg/960px-Xbox_Series_S_with_controller.jpg', 'The smaller, all-digital member of the Xbox Series family: no disc drive, a lower target resolution than the Series X, and a much smaller footprint.', 'https://en.wikipedia.org/wiki/Xbox_Series_X_and_Series_S', NULL),
  (14, 'Red Dead Redemption 2', 'game', 'PlayStation', 'Good', 2323, 4979, 4.9, '🤠', 'from-orange-600/30 to-red-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/library_600x900.jpg', 'Red Dead Redemption 2 is a 2018 action-adventure game developed and published by Rockstar Games. The game is the third entry in the Red Dead series and a prequel to the 2010 game Red Dead Redemption.', 'https://en.wikipedia.org/wiki/Red_Dead_Redemption_2', 1174180),
  (15, 'The Witcher 3: Wild Hunt', 'game', 'PC', 'Good', 1494, 2074, 4.9, '🐺', 'from-red-600/30 to-amber-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/library_600x900.jpg', 'The Witcher 3: Wild Hunt‍ is a 2015 action role-playing game developed and published by CD Projekt. It is the sequel to the 2011 game The Witcher 2: Assassins of Kings and the third game in The Witcher video game series, played in an open world with a third-person perspective.', 'https://en.wikipedia.org/wiki/The_Witcher_3%3A_Wild_Hunt', 292030),
  (16, 'Grand Theft Auto V', 'game', 'PlayStation', 'Good', 2074, 2904, 4.7, '🚔', 'from-lime-500/30 to-emerald-400/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/library_600x900.jpg', 'Grand Theft Auto V is a 2013 action-adventure game developed by Rockstar North and published by Rockstar Games. It is the seventh main entry in the Grand Theft Auto series, following 2008''s Grand Theft Auto IV, and the fifteenth instalment overall.', 'https://en.wikipedia.org/wiki/Grand_Theft_Auto_V', 271590),
  (17, 'Hogwarts Legacy', 'game', 'PlayStation', 'Mint', 2904, 4149, 4.6, '🧙', 'from-amber-500/30 to-yellow-400/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/990080/library_600x900.jpg', 'Hogwarts Legacy is a 2023 action role-playing video game developed by Avalanche Software and published by Warner Bros. Games under its Portkey Games label. It is part of the Wizarding World franchise, taking place a century before the Harry Potter novels.', 'https://en.wikipedia.org/wiki/Hogwarts_Legacy', 990080),
  (18, 'Sekiro: Shadows Die Twice', 'game', 'PC', 'Good', 2489, 4979, 4.8, '🥷', 'from-rose-600/30 to-slate-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/814380/library_600x900.jpg', 'Sekiro: Shadows Die Twice is a 2019 action-adventure game developed by FromSoftware. It was released in Japan by FromSoftware and internationally by Activision for the PlayStation 4, Windows and Xbox One in March 2019 and for Stadia in October 2020.', 'https://en.wikipedia.org/wiki/Sekiro%3A_Shadows_Die_Twice', 814380),
  (19, 'Hades', 'game', 'PC', 'Mint', 999, 1929, 4.9, '🔱', 'from-red-500/30 to-orange-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/library_600x900.jpg', 'Hades is a 2020 roguelike action role-playing game developed and published by Supergiant Games. It was released for macOS, Nintendo Switch, and Windows on September 17, 2020, following an early access release in December 2018.', 'https://en.wikipedia.org/wiki/Hades_(video_game)', 1145360),
  (20, 'Doom Eternal', 'game', 'Xbox', 'Good', 1659, 3319, 4.7, '👹', 'from-red-700/30 to-orange-600/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/782330/library_600x900.jpg', 'Doom Eternal is a 2020 first-person shooter game developed by id Software and published by Bethesda Softworks. It is the sequel to Doom (2016), and the seventh game in the Doom series.', 'https://en.wikipedia.org/wiki/Doom_Eternal', 782330),
  (21, 'Resident Evil 4', 'game', 'PlayStation', 'Mint', 3319, 4979, 4.9, '🧟', 'from-neutral-600/30 to-red-600/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/library_600x900.jpg', 'Resident Evil 4 is a 2023 survival horror game developed and published by Capcom. A remake of the 2005 game Resident Evil 4, it was released for PlayStation 4, PlayStation 5, Windows, and Xbox Series X/S on March 24, 2023.', 'https://en.wikipedia.org/wiki/Resident_Evil_4_(2023_video_game)', 2050650),
  (22, 'Marvel’s Spider-Man Remastered', 'game', 'PC', 'Good', 2489, 4149, 4.8, '🕷️', 'from-red-600/30 to-blue-600/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1817070/library_600x900.jpg', 'Marvel''s Spider-Man is a 2018 action-adventure game developed by Insomniac Games and published by Sony Interactive Entertainment. The first installment in the Marvel''s Spider-Man game series, it is based on the Marvel Comics character Spider-Man and tells an original narrative that is inspired by…', 'https://en.wikipedia.org/wiki/Marvel''s_Spider-Man_(video_game)', 1817070),
  (23, 'Horizon Zero Dawn', 'game', 'PlayStation', 'Good', 1245, 3319, 4.7, '🏹', 'from-orange-500/30 to-teal-400/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1151640/library_600x900.jpg', 'Horizon Zero Dawn is a 2017 action role-playing game developed by Guerrilla Games and published by Sony Interactive Entertainment. The first instalment in the Horizon video game series, it is set in a post-apocalyptic United States where large robotic machines dominate the Earth while humans live…', 'https://en.wikipedia.org/wiki/Horizon_Zero_Dawn', 1151640),
  (24, 'Death Stranding', 'game', 'PC', 'Good', 1659, 3319, 4.5, '📦', 'from-slate-500/30 to-amber-400/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1190460/library_600x900.jpg', 'Death Stranding is a 2019 action-adventure game developed by Kojima Productions and published by Sony Interactive Entertainment. It is the first game from director Hideo Kojima and Kojima Productions after their split from Konami in 2015.', 'https://en.wikipedia.org/wiki/Death_Stranding', 1190460),
  (25, 'Monster Hunter: World', 'game', 'PC', 'Good', 1494, 2489, 4.7, '🐲', 'from-emerald-600/30 to-lime-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/582010/library_600x900.jpg', 'Monster Hunter: World is a 2018 action role-playing game developed and published by Capcom. The fifth mainline installment in the Monster Hunter series, it was released worldwide for PlayStation 4 and Xbox One in January 2018, with a Windows version following in August 2018.', 'https://en.wikipedia.org/wiki/Monster_Hunter%3A_World', 582010),
  (26, 'Control', 'game', 'Xbox', 'Fair', 1245, 2489, 4.5, '🌀', 'from-red-500/30 to-slate-600/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/870780/library_600x900.jpg', 'Control is a 2019 action-adventure game developed by Remedy Entertainment. It follows Jesse Faden, the new Director of the Federal Bureau of Control (FBC), a secret U.S. government agency that investigates and contains phenomena that violate the normal laws of reality.', 'https://en.wikipedia.org/wiki/Control_(video_game)', 870780),
  (27, 'Hollow Knight', 'game', 'PC', 'Mint', 799, 1229, 4.9, '🐛', 'from-slate-600/30 to-cyan-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/367520/library_600x900.jpg', 'Hollow Knight is a 2017 Metroidvania video game developed and published by Australian independent development studio Team Cherry. The player controls a nameless insectoid warrior in exploring Hallownest, a fallen kingdom plagued by a supernatural disease.', 'https://en.wikipedia.org/wiki/Hollow_Knight', 367520),
  (28, 'Celeste', 'game', 'PC', 'Mint', 749, 1659, 4.8, '🏔️', 'from-indigo-500/30 to-pink-400/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/504230/library_600x900.jpg', 'Celeste is a 2018 platform video game developed and published by indie studio Maddy Makes Games. The player controls the player character Madeline, a young woman with anxiety and depression, who endeavors to climb Celeste Mountain, a fictional version of Mount Celeste.', 'https://en.wikipedia.org/wiki/Celeste_(video_game)', 504230),
  (29, 'Cuphead', 'game', 'Xbox', 'Good', 1245, 1659, 4.8, '☕', 'from-amber-500/30 to-red-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/268910/library_600x900.jpg', 'Cuphead is a 2017 run and gun game developed and published independently by Studio MDHR. The game follows its titular cup-head character and his brother Mugman, as they make a deal with the Devil to pay casino losses by repossessing the souls of runaway debtors.', 'https://en.wikipedia.org/wiki/Cuphead', 268910),
  (30, 'The Last of Us Part I', 'game', 'PlayStation', 'Mint', 3734, 4979, 4.8, '🍄', 'from-emerald-700/30 to-amber-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1888930/library_600x900.jpg', 'The Last of Us Part I is a 2022 action-adventure game developed by Naughty Dog and published by Sony Interactive Entertainment. A remake of the 2013 game The Last of Us, it features revised gameplay, including enhanced combat and exploration, and expanded accessibility options.', 'https://en.wikipedia.org/wiki/The_Last_of_Us_Part_I', 1888930),
  (31, 'Starfield', 'game', 'Xbox', 'Good', 3319, 5809, 4.2, '🚀', 'from-indigo-600/30 to-slate-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/library_600x900.jpg', 'Starfield is a 2023 action role-playing game developed by Bethesda Game Studios and published by Bethesda Softworks. In the game, the player character joins a group of space explorers who must venture 50 light-years around the Sol System to acquire mysterious artifacts.', 'https://en.wikipedia.org/wiki/Starfield_(video_game)', 1716740),
  (32, 'Lies of P', 'game', 'PC', 'Mint', 2904, 4979, 4.7, '🎭', 'from-slate-700/30 to-rose-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1627720/library_600x900.jpg', 'Lies of P is a 2023 action role-playing game developed by Neowiz and Nough and published by Neowiz. The story is loosely based on the 1883 Italian novel The Adventures of Pinocchio by Carlo Collodi, to whom it is dedicated.', 'https://en.wikipedia.org/wiki/Lies_of_P', 1627720),
  (33, 'Street Fighter 6', 'game', 'PlayStation', 'Good', 2904, 4979, 4.7, '🥋', 'from-yellow-500/30 to-blue-500/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1364780/library_600x900.jpg', 'Street Fighter 6 is a 2023 fighting game developed and published by Capcom. It is the seventh main entry in the Street Fighter franchise, following Street Fighter V (2016), and was released worldwide on June 2, 2023, for PlayStation 4, PlayStation 5, Windows and Xbox Series X/S, while an arcade…', 'https://en.wikipedia.org/wiki/Street_Fighter_6', 1364780),
  (34, 'Devil May Cry 5', 'game', 'Xbox', 'Good', 1659, 2904, 4.7, '😈', 'from-red-600/30 to-purple-600/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/601150/library_600x900.jpg', 'Devil May Cry 5 is a 2019 action-adventure game developed and published by Capcom. The game is the sixth installment overall and the fifth mainline installment in the Devil May Cry series.', 'https://en.wikipedia.org/wiki/Devil_May_Cry_5', 601150),
  (35, 'Stardew Valley', 'game', 'PC', 'Mint', 599, 1229, 4.9, '🌾', 'from-green-500/30 to-amber-400/30', 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/library_600x900.jpg', 'Stardew Valley is a 2016 farm life simulation video game developed by Eric "ConcernedApe" Barone. Players take the role of a character who inherits their deceased grandfather''s dilapidated farm.', 'https://en.wikipedia.org/wiki/Stardew_Valley', 413150),
  (36, 'Super Mario Odyssey', 'game', 'Nintendo', 'Good', 2904, 4149, 4.9, '🎩', 'from-red-500/30 to-yellow-400/30', 'https://upload.wikimedia.org/wikipedia/en/8/8d/Super_Mario_Odyssey.jpg', 'Super Mario Odyssey is a 2017 platform game developed and published by Nintendo for the Nintendo Switch. An installment in the Super Mario series, it follows Mario and his new ally Cappy—a sentient hat—as they journey across various kingdoms to save Princess Peach from Mario''s nemesis Bowser''s…', 'https://en.wikipedia.org/wiki/Super_Mario_Odyssey', NULL),
  (37, 'Animal Crossing: New Horizons', 'game', 'Nintendo', 'Mint', 3319, 4149, 4.8, '🍃', 'from-teal-400/30 to-lime-400/30', 'https://upload.wikimedia.org/wikipedia/en/1/1f/Animal_Crossing_New_Horizons.jpg', 'Animal Crossing: New Horizons is a 2020 social simulation game developed and published by Nintendo for the Nintendo Switch. It is the fifth main installment in the Animal Crossing series, following Animal Crossing: New Leaf.', 'https://en.wikipedia.org/wiki/Animal_Crossing%3A_New_Horizons', NULL),
  (38, 'Super Smash Bros. Ultimate', 'game', 'Nintendo', 'Good', 3319, 4979, 4.9, '💥', 'from-orange-500/30 to-red-600/30', 'https://upload.wikimedia.org/wikipedia/en/5/50/Super_Smash_Bros._Ultimate.jpg', 'Super Smash Bros. Ultimate is a 2018 crossover fighting game developed by Bandai Namco Studios and Sora Ltd. and published by Nintendo for the Nintendo Switch. It is the fifth installment in the Super Smash Bros. series, succeeding Super Smash Bros. for Nintendo 3DS and Wii U (2014).', 'https://en.wikipedia.org/wiki/Super_Smash_Bros._Ultimate', NULL),
  (39, 'Splatoon 3', 'game', 'Nintendo', 'Good', 3319, 4979, 4.6, '🦑', 'from-fuchsia-500/30 to-cyan-400/30', 'https://upload.wikimedia.org/wikipedia/en/4/4f/Splatoon.3.jpg', 'Splatoon 3 is a 2022 third-person shooter game developed and published by Nintendo for the Nintendo Switch. It is the third game in the Splatoon series and the sequel to Splatoon 2.', 'https://en.wikipedia.org/wiki/Splatoon_3', NULL),
  (40, 'Nintendo Switch', 'console', 'Nintendo', 'Good', 18259, 24899, 4.7, '🔴', 'from-red-500/40 to-blue-500/30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Nintendo-Switch-Console-Docked-wJoyConRB.jpg/960px-Nintendo-Switch-Console-Docked-wJoyConRB.jpg', 'The Nintendo Switch is a video game console developed by Nintendo and released worldwide in most regions on March 3, 2017.', 'https://en.wikipedia.org/wiki/Nintendo_Switch', NULL),
  (41, 'Nintendo Switch Lite', 'console', 'Nintendo', 'Good', 13279, 16599, 4.5, '💛', 'from-yellow-400/40 to-neutral-500/30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Nintendo_Switch_Lite_Grey_-_01.jpg/960px-Nintendo_Switch_Lite_Grey_-_01.jpg', 'A lighter, handheld-only Nintendo Switch with the controls built in. It does not dock to a TV.', 'https://en.wikipedia.org/wiki/Nintendo_Switch', NULL),
  (42, 'Xbox One X', 'console', 'Xbox', 'Good', 16599, 33199, 4.6, '🎮', 'from-neutral-700/40 to-green-500/30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Microsoft-Xbox-One-X-Console-01.jpg/960px-Microsoft-Xbox-One-X-Console-01.jpg', 'The Xbox One is a home video game console developed by Microsoft. Announced in May 2013, it is the successor to Xbox 360 and the third console in the Xbox series.', 'https://en.wikipedia.org/wiki/Xbox_One', NULL),
  (43, 'PlayStation 3 Super Slim', 'console', 'PlayStation', 'Fair', 9959, 20749, 4.3, '🎮', 'from-slate-700/40 to-blue-500/30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Sony-PlayStation-PS3-SuperSlim-Console-FL.jpg/960px-Sony-PlayStation-PS3-SuperSlim-Console-FL.jpg', 'The PlayStation 3 (PS3) is a home video game console developed and marketed by Sony Computer Entertainment (SCE). It is the successor to the PlayStation 2, and both are part of the PlayStation brand of consoles.', 'https://en.wikipedia.org/wiki/PlayStation_3', NULL),
  (44, 'Steam Deck', 'console', 'PC', 'Mint', 33199, 41499, 4.8, '🎒', 'from-blue-600/40 to-slate-500/30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Steam_Deck_%28front%29.png/960px-Steam_Deck_%28front%29.png', 'The Steam Deck is a handheld gaming computer produced by Valve Corporation, designed to run games available on its Steam storefront. Built upon the experiences gained from Valve''s earlier ventures with the original 2015 Steam Machine and the Steam Controller, the Steam Deck integrates a custom AMD…', 'https://en.wikipedia.org/wiki/Steam_Deck', NULL)
ON CONFLICT (id) DO UPDATE SET
  title          = EXCLUDED.title,
  type           = EXCLUDED.type,
  platform       = EXCLUDED.platform,
  "condition"    = EXCLUDED."condition",
  price          = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  rating         = EXCLUDED.rating,
  emoji          = EXCLUDED.emoji,
  accent         = EXCLUDED.accent,
  image_url      = EXCLUDED.image_url,
  description    = EXCLUDED.description,
  wikipedia_url  = EXCLUDED.wikipedia_url,
  steam_appid    = EXCLUDED.steam_appid;
