name: Manual DevOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./Back-end

    steps:
      - name: Post-deployment directory cleanup
        working-directory: ${{ github.workspace }}
        run: |
          echo "Cleaning up workspace..."
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-ts-backend:latest .

      - name: Deploy Container
        run: |
          docker stop my-backend-container || true
          docker rm my-backend-container || true
          docker run -d --name my-backend-container -p 4000:4000 --restart unless-stopped my-ts-backend:latest
